### ISSUE TITLE
Your DNS servers are failing

### ISSUE THREAD

**Issue by watermelonjuice** [fresh-standard/fresh-standard.github.io#1]
*\* server can't find freshstandard.org: SERVFAIL

**Comment by hacksalot** [comment]
Thanks, this should start resolving shortly. Rogue NS entry from our previous setup.

**Comment by watermelonjuice** [comment]
You have the same problem with your other sites. e.g. hackmyresume

**Comment by hacksalot** [comment]
Also fixed as we finish transitioning sites off our hold host and in some cases back off of GH Pages. The other sites should come up in the next few hours.

**Comment by watermelonjuice** [comment]
Are you in charge of http://fluentcv.com/ ? It's still down.
